#!/usr/bin/env zsh

cd /opt/dev/betterworks/code/warehouse-engine
pyenv virtualenvwrapper
source /Users/logan/.pyenv/versions/3.10.1/bin/virtualenvwrapper.sh
workon wh-engine
export PYTHONPATH="$(pwd)"
source source-env env.local.private
