#!/usr/bin/env zsh

tmux new-window \; \
    split-window -v \; \
    split-window -h \; \
    select-pane -t 0 \; \
    split-window -h \; \
    rename-window 'wh execution' \; \
    select-pane -t 0 \; \
    send-keys 'source ~/.bin/bootstrap_wh_term' C-m \; \
    select-pane -t 1 \; \
    send-keys 'source ~/.bin/bootstrap_wh_term' C-m \; \
    select-pane -t 2 \; \
    send-keys 'source ~/.bin/bootstrap_wh_term' C-m \; \
    select-pane -t 3 \; \
    send-keys 'source ~/.bin/bootstrap_wh_term' C-m \; \
    select-pane -t 0 \; \
    send-keys 'make worker | tail -f logs/worker.log' C-m \; \
    select-pane -t 1 \; \
    send-keys 'make worker-monitor | tail -f logs/worker-monitor.log' C-m \; \
    select-pane -t 2 \; \
    send-keys 'HOSTNAME=betterhyphy make dispatcher' C-m \; \
    select-pane -t 3 \; \
    send-keys 'make dev-monitor' C-m \; \
