#!/usr/bin/env bash

silent=false
files=()
for arg in "$@"; do
    if [[ "$arg" == "-s" || "$arg" == "--silent" ]]; then
        silent=true
    else
        files+=("$arg")
    fi
done

for file in "${files[@]}"; do
	while IFS= read -r line; do
			[[ -z "$line" || "$line" =~ ^# ]] && continue
			$silent || echo "$line"
			export "$line"
	done < <(cat "$file" && echo)
done
