#!/usr/bin/env bash

silent=false
if [[ "$1" == "-s" || "$1" == "--silent" ]]; then
		silent=true
		shift
fi

while IFS= read -r line; do
		[[ -z "$line" || "$line" =~ ^# ]] && continue
		$silent || echo "$line"
		export "$line"
done < <(cat "$@" && echo)
