#! /usr/bin/env bash

bold=$(tput bold)
normal=$(tput sgr0)
yellow=$(tput setaf 3)
red=$(tput setaf 1)
green=$(tput setaf 2)

total_tests=0
total_failures=0
total_time=0

skip_repos=""
other_args=""
for arg in "$@"; do
	if [[ $arg == "--skip="* ]]; then
		skip_repos=$(echo "$arg" | cut -d'=' -f2 | tr ',' '|')
		shift
	else
		other_args+=" $arg"
	fi
done

for dir in */; do
	repo_name=$(basename "$dir")
	if [[ $skip_repos =~ (^|[|,])$repo_name($|[|,]) ]]; then
		continue
	fi	

	echo "🚀 ${bold}testing module: ${yellow}${dir%/}${normal}"

	output=$(cd "${dir}" && gotestsum -- -v -race ${other_args} ./...)
	echo "$output"
	
	tests=$(ggrep -oP 'DONE \K\d+' <<< "$output")
	failures=$(ggrep -oP '([0-9]+) failures' <<< "$output" | ggrep -oP '\d+')
	time=$(perl -pe 's/.*DONE.*?([\d.]+)s$/$1/g' <<< "$output" | tail -n 1)
	
	total_tests=$((total_tests + tests))
	total_failures=$((total_failures + failures))
	total_time=$(bc -l <<< "$total_time + $time")
	echo ""
done

echo "${bold}${green}Total tests:    ${total_tests}${normal}"
if [ "${total_failures}" -ne 0 ]; then
	echo "${bold}${red}Total failures: ${total_failures}${normal}"
fi
echo "Total time:     ${yellow}${total_time}s${normal}"
